"""Dump the curated demo state to a re-seedable SurrealQL file.

Survives `make db-reset` or any other agent wiping the DB. Run after every
significant manual curation. Apply with:

    surreal sql --endpoint http://localhost:8000 --username $SURREAL_USER \\
                --password $SURREAL_PASS --namespace $SURREAL_NS \\
                --database $SURREAL_DB < knowledge_graph/seed/demo_snapshot.surql

Or via Python:
    cd knowledge_graph && uv run python -m candidates.snapshot --apply

Usage to dump:
    cd knowledge_graph && uv run python -m candidates.snapshot
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
from pathlib import Path

from surrealdb import AsyncSurreal

log = logging.getLogger("candidates.snapshot")
logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

OUT_PATH = Path(__file__).resolve().parent.parent / "seed" / "demo_snapshot.surql"

# Entities tagged for the curated demo (hand-created or specifically renamed/typed)
DEMO_ENTITY_NAMES = [
    "Luma Hackathon: To The Americas!",
    "microbots",
    "Luma",
    "Devin",
    "Cognition",
    "Devin.ai Integration",
    "Encode Hub",
    "Nader Dabit",
    "Unicorn Mafia",
    "j-d0g/microbots",
    "microbot-harness-frontend",
]

DEMO_WIKI_PATHS = [
    "automations.md",
    "entities/event/luma-hackathon.md",
]


def _to_surql(value):
    """Render a Python value as a SurrealQL literal."""
    if value is None:
        return "NONE"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)  # JSON strings are valid SurrealQL strings
    if isinstance(value, list):
        return "[" + ", ".join(_to_surql(v) for v in value) + "]"
    if isinstance(value, dict):
        items = ", ".join(f"{json.dumps(k)}: {_to_surql(v)}" for k, v in value.items())
        return "{" + items + "}"
    # datetimes from surrealdb come as strings already (ISO format)
    return json.dumps(str(value))


def _as_create(table: str, row: dict) -> str:
    rid = str(row.pop("id"))
    # Strip auto-managed fields; recreated by defaults
    for f in ("created_at", "updated_at", "content_hash", "revision", "token_estimate"):
        row.pop(f, None)
    return f"CREATE {rid} CONTENT {_to_surql(row)};"


async def dump(db: AsyncSurreal) -> str:
    chunks = [
        "-- Curated demo snapshot. Generated by candidates/snapshot.py.",
        "-- Re-applies the hand-curated subset after a DB wipe.",
        "-- Idempotent: deletes existing rows by id before recreating.",
        "",
    ]

    # -- automation_candidate (all open) ---
    rows = await db.query("SELECT * FROM automation_candidate WHERE status = 'open';")
    chunks.append(f"-- {len(rows or [])} automation candidates")
    for r in rows or []:
        rid = str(r["id"])
        chunks.append(f"DELETE {rid};")
        chunks.append(_as_create("automation_candidate", dict(r)))
    chunks.append("")

    # -- evidence edges ---
    for edge_table in ("candidate_evidence_chat", "candidate_evidence_entity", "candidate_evidence_memory"):
        edges = await db.query(f"SELECT in, out FROM {edge_table};")
        chunks.append(f"-- {len(edges or [])} {edge_table} edges")
        for e in edges or []:
            chunks.append(f"RELATE {e['in']} -> {edge_table} -> {e['out']};")
        chunks.append("")

    # -- demo entities (typed + tagged) ---
    placeholders = ", ".join(json.dumps(n) for n in DEMO_ENTITY_NAMES)
    rows = await db.query(f"SELECT * FROM entity WHERE name IN [{placeholders}];")
    chunks.append(f"-- {len(rows or [])} demo entities")
    for r in rows or []:
        rid = str(r["id"])
        chunks.append(f"DELETE {rid};")
        chunks.append(_as_create("entity", dict(r)))
    chunks.append("")

    # -- demo wiki pages ---
    placeholders = ", ".join(json.dumps(p) for p in DEMO_WIKI_PATHS)
    rows = await db.query(f"SELECT * FROM wiki_page WHERE path IN [{placeholders}];")
    chunks.append(f"-- {len(rows or [])} demo wiki pages")
    for r in rows or []:
        rid = str(r["id"])
        chunks.append(f"DELETE {rid};")
        chunks.append(_as_create("wiki_page", dict(r)))
    chunks.append("")

    return "\n".join(chunks)


async def apply_snapshot(db: AsyncSurreal) -> None:
    if not OUT_PATH.exists():
        log.error("No snapshot at %s — run dump first.", OUT_PATH)
        sys.exit(1)
    sql = OUT_PATH.read_text()
    # SurrealDB driver runs multi-statement queries fine
    await db.query(sql)
    log.info("Applied snapshot from %s", OUT_PATH)


async def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--apply", action="store_true", help="Apply existing snapshot instead of dumping")
    args = p.parse_args()

    url = os.environ.get("SURREAL_URL", "ws://localhost:8000/rpc")
    db = AsyncSurreal(url)
    await db.connect()
    await db.signin({"username": os.environ["SURREAL_USER"], "password": os.environ["SURREAL_PASS"]})
    await db.use(os.environ["SURREAL_NS"], os.environ["SURREAL_DB"])

    if args.apply:
        await apply_snapshot(db)
    else:
        sql = await dump(db)
        OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATH.write_text(sql)
        log.info("Snapshot written to %s (%d bytes)", OUT_PATH, len(sql))

    await db.close()


if __name__ == "__main__":
    asyncio.run(main())
